consulta/urls.py
from django.conf.urls import url
from django.urls import path
from .agenda import EventFeed
from . import views

app_name = 'consulta'

urlpatterns =[
    #path('',views.index,name='index'),
    path('',views.consulta_designacao,name='consulta_designacao'),
    path('consulta_dia/',views.consulta_dia,name='consulta_dia'),
    path('consulta_designacao/',views.consulta_designacao,name='consulta_designacao'),
    path('retorno_designacao/',views.retorno_designacao,name='retorno_designacao'),
    path('resultado/',views.resultado,name='resultado'),
    path('agenda/evento.ics',EventFeed()),
    path('retorno/',views.scheduler,name='scheduler'),
    path('ajax/',views.ajax_test,name='ajax_test'),
    path('gerar_pdf',views.gerar_pdf,name='gerar_pdf')
]

main/urls.py
from django.urls import path,include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
	#path('admin/consulta/',include('consulta.urls',namespace='index')),
	path('consulta/',include('consulta.urls')),
    path('admin/cadastro/',include('cadastro.urls')),
    #path('admin/calendario/',include('calendario.urls')),
    path(r'admin/', admin.site.urls),
    path('admin/password_reset/',auth_views.PasswordResetView.as_view(),name='admin_password_reset',),
    path('admin/password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done',),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm',),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete',),
]

admin.site.site_header='Testemunho Publico'
admin.site.site_title='Testemunho Publico'
next_day = 'dia assim'

consulta/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

class consulta(models.Model):
    id = models.AutoField(primary_key=True)
    mes = models.CharField(max_length=25,null=True,verbose_name='mes',blank=True)

consulta/forms.py
from django import forms
from cadastro.models import designacao,irmaos
from django.forms import widgets

class designacaoForms(forms.Form):
    ano = forms.CharField(label='Ano',required=False)
    mes = forms.ChoiceField(choices=((1,'Janeiro'),(2,'Fevereiro'),(3,'Março'),(4,'Abril'),(5,'Maio'),(6,'Junho'),(7,'Julho'),(8,'Agosto'),(9,'Setembro'),(10,'Outubro'),(11,'Novembro'),(12,'Dezembro')),required=False,initial='2',widget=forms.Select(attrs={'style': 'border-color: blue;','placeholder': 'defina o mes na pesquisa'}))
    tpPesquisa = forms.ChoiceField(choices=((1,'tabela completa'),(2,'filtrar por nome')),label='Tipo Pesquisa',initial='filtrar por nome',required=False,widget=forms.Select(attrs={'style': 'border-color: orange;'}),)
    sel_irmaos = forms.ModelChoiceField(queryset=irmaos.objects.all().filter(habilitado='True').order_by('nm'),required=False,label='selecione o Irmao',widget=forms.Select(attrs={'readonly':'readonly'}))

consulta/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# from django.conf import settings
# from django.contrib.sites.models import Site
from cadastro.tratamento import consulta_irmaos_dia_semana
from cadastro.models import designacao,irmaos
#from calendario.models import calendario
from django.shortcuts import render, redirect, get_object_or_404,render_to_response
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.template import RequestContext
from django.middleware import csrf
from consulta.forms import designacaoForms
from django.utils import timezone
from datetime import datetime
from django.db.models import Q
from django_ical.views import ICalFeed

from .agenda import EventFeed
from urllib.request import urlopen
from bs4 import BeautifulSoup
from django_ical import feedgenerator
from django.template.defaultfilters import slugify
import calendar,locale, requests,csv,json,os,vobject,time,pytz,re
from icalendar import Calendar, Event
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from django.views.generic import View

from .tratamento import make_pdf

def index(request):
    aviso = 'aviso'
    return render(request,'consulta/index.html')

def consulta_dia(request):
    return render(request,'consulta/consulta_dia.html')

def consulta_designacao(request):
    locale.setlocale(locale.LC_ALL,'pt_BR.UTF-8')
    grupo = request.user.groups.values_list('name',flat=True)

    hoje = timezone.now()
    m = hoje.month
    a = hoje.year
    if request.method=='POST':
        form = designacaoForms(request.POST)
        return render(request,'consulta/consulta_designacao.html',{'form':form,'grupo':grupo})
    else:
        form = designacaoForms(initial={'ano':int(a),'mes':m})
        return render(request,'consulta/consulta_designacao.html',{'form':form,'grupo':grupo})

def retorno_designacao(request):
    locale.setlocale(locale.LC_ALL,'pt_BR.UTF-8')
    BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    BASE_DIR = os.path.join(BASE,'medias')
    if request.method=='POST':
        irmao = request.POST['sel_irmaos']
        m = int(request.POST['mes'])
        a = request.POST['ano']
        p = request.POST['tpPesquisa']
        mes = calendar.month_name[m]

        if len(irmao)==0:
            i=0
        else:
            i = [v['nm'] for v in irmaos.objects.values('nm').filter(pk=irmao)][0]
        if p=='1': #Pesquisa completa
            mensagem = {'completa':'Tipo de Pesquisa - COMPLETA'}
            form = designacao.objects.values().filter(ano=a,mes=mes).order_by('ano','mes','dia_mes','dia_semana')
            return render(request, 'consulta/retorno_designacao.html', {'form': form,'mensagem':mensagem})
        elif p=='2':  #Pesquisa por Irmao
            if len(irmao)<1:
                mensagem = {'pessoa':'favor definir o irmao'}
                form = designacao.objects.values().filter(Q(p1=i)|Q(p1_1=i)|Q(p1_2=i)|Q(p2=i)|Q(p2_1=i)|Q(p3=i)|Q(p3_1=i)|Q(p4=i)|Q(p4_1=i)|Q(p5=i)|Q(p5_1=i),ano=a,mes=mes).order_by('ano','mes','dia_mes','dia_semana')
            else:
                mensagem = {'irmao':str(i)}
                form = designacao.objects.values().filter(Q(p1=i)|Q(p1_1=i)|Q(p1_2=i)|Q(p2=i)|Q(p2_1=i)|Q(p3=i)|Q(p3_1=i)|Q(p4=i)|Q(p4_1=i)|Q(p5=i)|Q(p5_1=i),ano=a,mes=mes).order_by('ano','mes','dia_mes','dia_semana')
                f_filter = [ {f['ano'],f['mes'],f['dia_semana'],f['dia_mes']} for f in form]
                contexto = form
                ctxt_periodos =[]
                ctxt_periodos_filtro = []
                for ln in contexto:
                    mes = time.strptime(ln['mes'], "%B").tm_mon
                    day_b = '{}-{}-{}'.format(ln['dia_mes'],mes,ln['ano'])
                    day_a = datetime.strptime(day_b,'%d-%m-%Y')
                    ctxt = {i:{'dia':str(day_a),'semana':ln['dia_semana'],
                            'periodo1':[ln['p1'],ln['p1_1'],ln['p1_2']],
                            'periodo2':[ln['p2'],ln['p2_1']],
                            'periodo3':[ln['p3'],ln['p3_1']],
                            'periodo4':[ln['p4'],ln['p4_1']],
                            'periodo5':[ln['p5'],ln['p5_1']]}}
                    ctxt_periodos.append(ctxt)
                #abrir a lista gerada e na lista foi feito um IF com a chave principal e os conteudos se igualarem
                for linhas in ctxt_periodos:
                    for ch,valores in linhas.items():
                        f = [{k:v} for k,v in valores.items() if k=='dia' or k=='semana' or re.search(i,str(v))]
                        ctxt_periodos_filtro.append(f)
                            
                with open(os.path.join(BASE_DIR,'calendario.json'),'w') as fl:
                    json.dump(ctxt_periodos,fl,indent=4)
            form_filtro = ctxt_periodos_filtro
            return render(request,'consulta/retorno_designacao.html',{'form_filtro':form_filtro,'mensagem':mensagem})
    else:
        mensagem = {'semretorno':'sem resposta'}
        return render(request,'consulta/retorno_designacao',{'mensagem':mensagem})

def resultado(request):
    if 'dia' in request.POST:
        d = str(request.POST['dia'])
        irmaos = consulta_irmaos_dia_semana(d)
    return render(request, 'consulta/resultado.html',{'irmaos':irmaos})


# def make_calendar_object(event_id):
#     event = get_object_or_404(calendario, pk=id)
#
#     site = Site.objects.get_current()
#
#     site_token = site.domain.split('.')
#     site_token.reverse()
#     site_token = '.'.join(site_token)
#
#     cal = Calendar()
#     cal.add('prodid', '-//%s Events Calendar//%s//' % (site.name, site.domain))
#     cal.add('version', '2.0')
#
#     eventObj = Event()
#     eventObj.add('summary', event.name)
#     eventObj.add('location', event.location)
#     eventObj.add('dtstart', event.start_datetime)
#     eventObj.add('dtend', event.end_datetime)
#     eventObj.add('dtstamp', event.created_datetime)
#     eventObj['uid'] = '%dT%d.events.%s' % (event.id, random.randrange(111111111, 999999999), site_token)
#     eventObj.add('priority', 5)
#
#     cal.add_component(eventObj)
#
#     output = ""
#     for line in cal.content_lines():
#         if line:
#             output += line + "\n"
#     return output


def create_ics(data):
    cal = vobject.iCalendar()
    utc = vobject.icalendar.utc
    d = datetime.strptime(data['dia'],'%Y-%m-%d %H:%M:%S')
    dia_agenda = datetime(d.year, d.month, d.day,tzinfo=utc)
    cal.add('method').value = 'PUBLISH'
    vevent = cal.add('vevent')
    start = cal.vevent.add('dtstart')
    start.value = datetime(d.year,d.month,d.day,tzinfo=utc)
    sum = cal.vevent.add('summary')
    sum.value= data['tp']
    desc = cal.vevent.add('description')
    desc.value = data['periodo']
    return cal.serialize()
    #cal.add('method').value = 'PUBLISH'
    #vevent = cal.add('vevent')
    #vevent.add('dtstart').value = '20050404T080000'
    ##vevent.add('dtstart').value = dia_agenda
    #vevent.add('dtend').value = dia_agenda
    #vevent.add('dtstamp').value = dia_agenda
    #vevent.add('summary').value = 'Testemunho publico - minha designacao'


    
def scheduler(request):
    if request.method=='POST':
        print(request.session)
    BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    BASE_DIR = os.path.join(BASE,'medias')
    #context = RequestContext(request)
    lista_calendario = []
    todos_agendamentos=''
    with open(os.path.join(BASE_DIR,'calendario.json')) as fl:
        calendario = json.load(fl)
        for irmao in calendario:
            for k,pers in irmao.items():
                print('Irmao {}'.format(k))
                sel = k
                for per,val in pers.items():
                    print('Periodo {}'.format(per,val))
                    if per =='dia':
                        dd=val
                    if re.search(sel,str(val)):
                        print('registro localizado {}'.format(val))
                        contexto={'dia':dd,'tp':'Testemunho publico - designacao de '+str(sel),'periodo':str(per)+'='+str(val[0])}
                        lista_calendario.append(contexto)

    if isinstance(lista_calendario,list):
        for item in lista_calendario:
            grava_calendario = create_ics(item)
            todos_agendamentos+=grava_calendario
            print('gravar no calendario {}'.format(grava_calendario))

        response = HttpResponse(todos_agendamentos,content_type='text/calendar')
        response['Filename']=os.path.join(BASE_DIR,'calendario_hoje.ics')
        response['Content-Disposition']='attachment;filename=filename.ics'
    return response
    
    #if request.method=='POST':
    #    print('retorno POST com sucesso')
    #    print('post: %s'%request.POST)
    #    print('Sessao %s'%request.session)
    #    return render(request,"consulta/retorno.html",{'lista_calendario':lista_calendario})
    #else:
    #    return render_to_response("consulta/retorno.html", context_dict, context)

def gerar_pdf(request):
    BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    BASE_DIR = os.path.join(BASE,'medias')
    #context = RequestContext(request)
    lista_calendario = []
    todos_agendamentos=''
    with open(os.path.join(BASE_DIR,'calendario.json')) as fl:
        calendario = json.load(fl)
        for irmao in calendario:
            for k,pers in irmao.items():
                print('Irmao {}'.format(k))
                sel = k
                for per,val in pers.items():
                    print('Periodo {}'.format(per,val))
                    if per =='dia':
                        dd=val
                    if re.search(sel,str(val)):
                        print('registro localizado {}'.format(val))
                        contexto={'dia':dd,'tp':'Testemunho publico - designacao de '+str(sel),'periodo':str(per)+'='+str(val[0])}
                        lista_calendario.append(contexto)

templates/consulta/consulta_designacao.html
{% extends "admin/base_site.html" %}
{% load i18n static custom_tags%}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static " admin /css/dashboard.css" %}" />{% endblock %}
{% block coltype %}colMS{% endblock %}
{% block bodyclass %}{{ block.super }} dashboard{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Publico</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">

    <div class="app-{{ app.app_label }} module">
        <table>
            <caption>Veja as proximas designacoes</caption>
            <tr class="model-{{model.object_name|lower}}">
                <th scope="row">Amanha : {%for line in instance.content|next %}{{line}}{%endfor%}</th>
                <td>&nbsp;</td>
                <td></td>

            </tr>
        </table>
    </div>


    {%if mensagem%}<p> Tipo de pesquisa selecionada: {{mensagem}}</p>{%endif%}

    <div class="app-{{ app.app_label }} module">
        <table>
            <caption>Faça sua pesquisa aqui</caption>
            <tr class="model-{{model.object_name|lower}}">
                <th scope="row"><h3>Usuario: {{request.user}}. Grupo: {{grupo}}</h3></th>
                </tr>
</table>
            <form method="post" class="post-form" action="{%url 'consulta:retorno_designacao'%}">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Localizar" class="save btn btn-default">
            </form>
    </div>

    
    <!--
    <a href="../../consulta/agenda/evento.ics">clique aqui</a>
    -->
    {% endblock %}

templates/consulta/consulta_dia.html
{% extends "../admin/base_site.html" %}
{% load i18n static %}


{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <h1>Faça a pesquisa de irmãos disponiveis por dia</h1>
    <table id="result_list">
        <tr>
    <form action="{%url 'consulta:resultado'%}" method="post" novalidate>
        {%csrf_token%}
        <td><input type="radio" name="dia" value="Segunda-feira">Segunda-feira</td>
        <td><input type="radio" name="dia" value="Terca-feira">Terca-feira</td>
        <td><input type="radio" name="dia" value="Quarta-feira">Quarta-feira</td>
        <td><input type="radio" name="dia" value="Quinta-feira">Quinta-feira</td>
        <td><input type="radio" name="dia" value="Sexta-feira">Sexta-feira</td>
        <td><input type="radio" name="dia" value="Sabado">Sabado-feira</td>
        <td><input type="radio" name="dia" value="Domingo">Domingo</td>
        <td><input type="submit" value="enviar"></td>

    </form>
        </tr>
    </table>
</div>
{%endblock%}


{%block sidebar%}
<div id="content-related">
    <p>conteudo relacionado</p>
</div>
{%endblock%}
{% block nav-global %}{% endblock %}

templates/consulta/index.html
{% extends "../admin/base_site.html" %}
{% load i18n static %}


{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <h1>pagina principal da consulta</h1>
     </div>
{%endblock%}


{%block sidebar%}
<div id="content-related">
    <p>conteudo relacionado</p>
</div>
{%endblock%}
{% block nav-global %}{% endblock %}

templates/consulta/minha_designacao.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static " admin /css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
    <p>frame principal</p>
    <p>minha designacao</p>
    </div>

    {% endblock %}

    {% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <p>lateral</p>e
        </div>
    </div>
    {%endblock%}

templates/consulta/placed.html
{% extends "admin/base_site.html" %}
{% load i18n static%}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("#div1").load("file:///C:/Daniel/projetos/testemunhoweb-projeto/testemunhoweb/templates/consulta/demo_test.txt #p1");
  });
});
</script>
</head>
<div id="content-main">
    {{context}}

    <div id="div1"><h2>Let jQuery AJAX Change This Text</h2></div>

<button>Get External Content</button>

</div>
{%endblock%}

templates/consulta/resultado.html
{% extends "../admin/base_site.html" %}
{% load i18n static %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{%block content%}
<head>
<title>Testemunho Publico</title>
</head>

<div class="results">
    <table id="result_list">
        <thead>
        <tr>
            <td>Dia semana</td>
            <td>Irmao</td>
            <td>Estado Civil</td>
            <td>Conjuge</td>
            <td>Genero</td>
            <td>Qte Maximo</td>
            <td>Preferencial</td>
            <td>Privilegio</td>
            <td>Dianteira</td>
            <td>P1</td>
            <td>P1</td>
            <td>P1</td>
            <td>P2</td>
            <td>P2</td>
            <td>P3</td>
            <td>P3</td>
            <td>P4</td>
            <td>P4</td>
            <td>P5</td>
            <td>P5</td>
        </tr>
        </thead>
        <tbody>
        <tr><td >{{ result.form.non_field_errors }}</td></tr>
        {%for irmao in irmaos%}
        <tr class="{% cycle 'row1' 'row2' %}">
            <td>{{irmao.dia_semana}}</td>
            <td>{{irmao.irmao__nm}}</td>
            <td>{{irmao.irmao__estado_civil}}</td>
            <td>{{irmao.irmao__conjuge}}</td>
            <td>{{irmao.irmao__gr}}</td>
            <td>{{irmao.irmao__maximo}}</td>
            <td>{{irmao.preferencial}}</td>
            <td>{{irmao.irmao__privilegio}}</td>
            <td>{{irmao.irmao__dianteira}}</td>
            <td>{{irmao.p1}}</td>
            <td>{{irmao.p1_1}}</td>
            <td>{{irmao.p1_2}}</td>
            <td>{{irmao.p2}}</td>
            <td>{{irmao.p2_1}}</td>
            <td>{{irmao.p3}}</td>
            <td>{{irmao.p3_1}}</td>
            <td>{{irmao.p4}}</td>
            <td>{{irmao.p4_1}}</td>
            <td>{{irmao.p5}}</td>
            <td>{{irmao.p5_1}}</td>
        </tr>
        {%endfor%}
        </tbody>
    </table>
</div>
{%endblock%}
{%block sidebar%}
<div id="content-related">
    <p>{{irmao.dia_semana}} - total de irmaos: {{irmaos.count}}</p>
</div>
{%endblock%}
    {% block footer %}<div id="footer"></div>{% endblock %}
{% block nav-global %}{% endblock %}

templates/consulta/retorno.html
{% extends "admin/base_site.html" %}
{% load i18n static custom_export_tags %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static " admin /css/dashboard.css" %}" />{% endblock %}
{% block coltype %}colMS{% endblock %}
{% block bodyclass %}{{ block.super }} dashboard{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Publico</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    {%if lista_calendario %}
    {%for item in lista_calendario%}
    <div class="{% cycle 'row1' 'row2' %}">
        {{item}}
        </div> 
        {%endfor%}
        {%endif%}
    </div>
    {%endblock%}

templates/consulta/retorno_designacao.html
{% extends "admin/base_site.html" %}
{% load i18n static custom_export_tags %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static " admin /css/dashboard.css" %}" />{% endblock %}
{% block coltype %}colMS{% endblock %}
{% block bodyclass %}{{ block.super }}dashboard{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Publico</a></h1>
{% endblock %}


<script type="text/javascript"
        src="{% static 'consulta/js/form.js' %}"
</script>

{% block content %}
<div id="content-main">
    {%if mensagem%}
    {%for m in mensagem.values%}
    <h3>Nome do irmao selecionado: {{m}}</h3>
    {%endfor%}
    {%endif%}

    <form action="{%url 'consulta:scheduler'%}" method="post" class="post_form">
        {%csrf_token%}
		{%if form_filtro%}
        <input type="submit" value="Gravar na AGENDA" class="save btn btn-default">
		{%for lista in form_filtro%}
        <div class="{% cycle 'row1' 'row2' %}">
            <table>
                <tr>
                    {%for key,val in lista.0.items%}
                    <td>{{key}}:</td>
                    <td>{{val}}</td>
                    {%endfor%}
                    {%for key,val in lista.1.items%}
                    <td>{{key}}:</td>
                    <td>{{val}}</td>
                    {%endfor%}
                    {%for key,val in lista.2.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.3.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.4.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.5.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.6.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.7.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.8.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.9.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.10.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.11.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.12.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.13.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.14.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}
                    {%for key,val in lista.15.items%}
                    <td>{{key}}:</td>
                    {%for v in val%}<td>{{v}}</td>{%endfor%}
                    {%endfor%}

                </tr>
            </table>
            {% endfor %}
            <button value="gerar_pdf" onclick="">
            <a href="{%url 'consulta:gerar_pdf'%}">gerar PDF</a>
            {% endif %}

            {% if form %}
            <table>
                <tr>
                    <th>ano</th>
                    <th>mes</th>
                    <th>dia_mes</th>
                    <th>dia_semana</th>
                    <th>Per 1</th>
                    <th>Per 1</th>
                    <th>Per 1</th>
                    <th>Per 2</th>
                    <th>Per 2</th>
                    <th>Per 3</th>
                    <th>Per 3</th>
                    <th>Per 4</th>
                    <th>Per 4</th>
                    <th>Per 5</th>
                    <th>Per 5</th>
                </tr>
                {% for retorno in form %}

                <tr>
                    <td>{{retorno.ano}}</td>
                    <td>{{retorno.mes}}</td>
                    <td>{{retorno.dia_mes}}</td>
                    <td>{{retorno.dia_semana}}</td>
                    <td>{{retorno.p1}}</td>
                    <td>{{retorno.p1_1}}</td>
                    <td>{{retorno.p1_2}}</td>
                    <td>{{retorno.p2}}</td>
                    <td>{{retorno.p2_1}}</td>
                    <td>{{retorno.p3}}</td>
                    <td>{{retorno.p3_1}}</td>
                    <td>{{retorno.p4}}</td>
                    <td>{{retorno.p4_1}}</td>
                    <td>{{retorno.p5}}</td>
                    <td>{{retorno.p5_1}}</td>
                </tr>
                {%endfor%}
            </table>
            {%endif%}
        </div>
    </form>
</div>
{%endblock%}
{% block nav-global %}{% endblock %}