cadastro/urls.py
from django.urls import path
from . import views
# from .exporting import EventFeed

app_name = 'cadastro'
urlpatterns =[
    #path('',views.designar,name='designar'),
    path('designar/',views.designar,name='designar'),
    path('gerador/',views.gerador,name='gerador'),
    path('showing/',views.showing,name='showing'),
    path('confirmacao/',views.confirmacao,name='confirmacao'),
    path('importar/',views.importar,name='importar'),
    path('gravar/',views.gravar,name='gravar')
    # path('novoevento', EventFeed(),name='novoevento'),
]

main/urls.py
from django.urls import path,include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
	#path('admin/consulta/',include('consulta.urls',namespace='index')),
	path('consulta/',include('consulta.urls')),
    path('admin/cadastro/',include('cadastro.urls')),
    #path('admin/calendario/',include('calendario.urls')),
    path(r'admin/', admin.site.urls),
    path('admin/password_reset/',auth_views.PasswordResetView.as_view(),name='admin_password_reset',),
    path('admin/password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done',),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm',),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete',),
]

admin.site.site_header='Testemunho Publico'
admin.site.site_title='Testemunho Publico'
next_day = 'dia assim'

testemunhoweb/cadastro/urls.py
from django.urls import path
from . import views
# from .exporting import EventFeed

app_name = 'cadastro'
urlpatterns =[
    #path('',views.designar,name='designar'),
    path('designar/',views.designar,name='designar'),
    path('gerador/',views.gerador,name='gerador'),
    path('showing/',views.showing,name='showing'),
    path('confirmacao/',views.confirmacao,name='confirmacao'),
    path('importar/',views.importar,name='importar'),
    # path('novoevento', EventFeed(),name='novoevento'),
]

cadastro/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals,absolute_import
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.shortcuts import render,reverse
import os, sys,openpyxl,re,calendar
from datetime import datetime
from .models import irmaos,dias,designacao
import json, csv
from openpyxl.styles import fills,PatternFill,Border, Side, Alignment, Protection, Font, Color, colors
from openpyxl import Workbook
from .tratamento import tratamento,spreadsheet_reader,consulta_irmaos,excessoes
from django.core.files.storage import FileSystemStorage
from django.core.serializers import serialize
import locale

def index(request):
    return 'index'

def designar(request):
    qs={}
    hoje =datetime.now()
    mes = hoje.strftime('%m')
    ano = hoje.strftime('%Y')
    qs = request.META['QUERY_STRING']
    return render(request,'cadastro/designar.html',{'qs':qs,'hoje':hoje,'mes':mes,'ano':ano})


def gerador(request):
    lista = consulta_irmaos()
    locale.setlocale(locale.LC_ALL,'pt_BR.UTF-8')
    BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    BASE_DIR = os.path.join(BASE,'medias')
    hoje = datetime.now()
    d = hoje.strftime('%d')
    qs = str(request.META['QUERY_STRING'])
    f = open(os.path.join(BASE_DIR,'lista_mes.json'),'w')
    planilha_dict = {}
    arqmes = {'campo':'nome'}
    mensagem = 'Mensagem de teste'
    external = sys.stdout
    sys.stdout = open(os.path.join(BASE_DIR,'backlog.log'),'w')
    arqmes = open(os.path.join(BASE_DIR,'mes.txt'),'w')
    lista_mes = []
    wbMes = Workbook()
    wsMes = wbMes.active
    thin_border = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'),bottom=Side(style='thin'))
    fill = PatternFill("solid", fgColor="DDDDDD")
    # mes_json = open(os.path.join(BASE_DIR,'planilha.json'),'w')

    if 'ano' in request.POST:
        mes = int(request.POST['mes'])
        mes_label = calendar.month_name[mes]
        ano = int(request.POST['ano'])
        planMes = os.path.join(BASE_DIR, mes_label) + '.xlsx'
        mensagem = mes_label
        ultimo_dia = calendar.monthrange(ano, int(mes))[1]
        campos = [f.name for f in dias._meta.get_fields()][3:]
        expurgo_dia = []
        designado_dia = []
        lista_segunda = {}; lista_terca = {};lista_quarta ={};lista_quinta ={}; lista_sexta ={};lista_sabado ={}
        planilha_dict={'ano':ano,'mes':mes,'nome mes':mes_label}
        # json.dump({'ano':ano},mes_json,indent=4)
        # json.dump({'mes':mes,'nome mes':mes_label},mes_json,indent=4)
        for dia_mes in range(1,ultimo_dia+1):
            dia_semana = calendar.weekday(int(ano), int(mes), dia_mes)
            if dia_semana==0:
                ds='Segunda-feira'
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia = lista_segunda # esta linha e usada para zerar a variavel lista_dia pois esta e usada para preenchimento do dia final
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_segunda = filled_day
                lista_dia = lista_segunda
                # lista_dia=sorted(lista_segunda.values()); print('lista segunda %s'%str(lista_dia))
                lista_dia = doublecheck(lista_segunda.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes,lista_dia)
                # swap_file(arqmes,filled_day)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                # json.dump(lista_segunda,mes_json,indent=4)
                planilha_dict[dia_mes]=lista_segunda
            elif dia_semana==1:
                ds='Terca-feira';print(ds)
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia = lista_terca
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_terca = filled_day
                lista_dia = lista_terca
                # lista_dia=sorted(lista_terca.values()); print('lista Terca %s'%lista_dia)
                lista_dia = doublecheck(lista_terca.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes,lista_dia)
                # swap_file(arqmes,filled_day)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                planilha_dict[dia_mes]=lista_terca
            elif dia_semana==2:
                ds='Quarta-feira';print(ds)
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia = lista_quarta
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_quarta = filled_day
                lista_dia = lista_quarta
                # lista_dia= sorted(lista_quarta.values()); print('lista quarta %s'%lista_dia)
                lista_dia = doublecheck(lista_quarta.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes, lista_dia)
                # swap_file(arqmes,filled_day)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                planilha_dict[dia_mes]=lista_quarta
            elif dia_semana==3:
                ds='Quinta-feira';print(ds)
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia = lista_quinta
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_quinta = filled_day
                lista_dia = lista_quinta
                # lista_dia= sorted(lista_quinta.values()); print('lista quinta %s'%lista_dia)
                # lista_dia = doublecheck(lista_quinta.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes, lista_dia)
                # swap_file(arqmes,filled_day)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                planilha_dict[dia_mes]=lista_quinta
            elif dia_semana==4:
                ds='Sexta-feira';print(ds)
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia=lista_sexta
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_sexta = filled_day
                lista_dia=lista_sexta
                # lista_dia = doublecheck(lista_sexta.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes, lista_dia)
                # swap_file(arqmes,filled_day)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                planilha_dict[dia_mes]=lista_sexta
            elif dia_semana==5:
                ds='Sabado';print(ds)
                dia=filling_header()
                dia['dia_mes']=dia_mes
                dia['dia_semana']=ds
                par = dia_mes % 2
                lista_dia = lista_sabado
                filled_day = filled_each_day(ds,dia,par,dia_mes,lista_dia,expurgo_dia,designado_dia)
                lista_dia=lista_sabado
                lista_sabado = filled_day
                lista_dia = lista_sabado
                # lista_dia= sorted(lista_sabado.values())
                print('lista sabado %s'%lista_dia)
                # print('Periodos em branco no dia %s %s: %s'%(str(dia_mes),ds,lista_dia.count('EMPTY')))
                lista_dia = doublecheck(lista_sabado.items(),ds,designado_dia)
                lista_mes.append(sorted(lista_dia.items()))
                swap_file(arqmes,lista_dia)
                swap_xls(lista_dia,wsMes,dia_mes)
                grava_json(BASE_DIR,lista_mes)
                planilha_dict[dia_mes]=lista_sabado
    with open(os.path.join(BASE_DIR,'planilha.json'),'w') as planilha_file:
        json.dump(planilha_dict,planilha_file,indent=4)
    with open(os.path.join(BASE_DIR,'planilha.json')) as planilha_file:
        planilha_retorno = json.load(planilha_file)
        for linha in planilha_retorno:
            print('linha da planilha gerada {}'.format(linha))
    contagem_irmaos(lista_mes)
    arqmes.close()
    sys.stdout.close()
    sys.stdout = external
    arqmes = open(os.path.join(BASE_DIR, 'mes.txt'), 'r')
    ultima_linha=wsMes.max_row+2
    rowdate = datetime.today()

    wsMes.merge_cells(start_row=ultima_linha+2,start_column=1,end_row=ultima_linha+2,end_column=2)
    wsMes.cell(row=ultima_linha,column=1).value='Data de geracao'
    wsMes.merge_cells(start_row=ultima_linha+2,start_column=3,end_row=ultima_linha+2,end_column=6)
    wsMes.cell(row=ultima_linha,column=3).value=rowdate
    wsMes.insert_rows(1,1)
    wsMes.merge_cells(start_row=1,start_column=1,end_row=1,end_column=3)
    wsMes.cell(row=1,column=1).value=mes_label
    wsMes.insert_rows(2,1)
    wsMes.cell(row=2,column=1).value='Dia Mes'
    wsMes.cell(row=2,column=2).value='Dia Semana'
    wsMes.merge_cells(start_row=2,start_column=3,end_row=2,end_column=5)
    wsMes.cell(row=2,column=3).value='Periodo 1'
    wsMes.merge_cells(start_row=2,start_column=6,end_row=2,end_column=7)
    wsMes.cell(row=2,column=6).value='Periodo 2'
    wsMes.merge_cells(start_row=2,start_column=8,end_row=2,end_column=9)
    wsMes.cell(row=2,column=8).value='Periodo 3'

templates/cadastro/confirmacao.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}
{% block content %}
<div id="content-main">
    <p>Os irmaos abaixo foram incluídos na base de dados com o usuario {{request.user}} </p>

    {%if myDictAll%}
	<table>
    {%for line in myDictAll%}
    <tr class="{% cycle 'row1' 'row2' %}">
    <td>{{line.dia_mes}}</td>
    <td>{{line.dia_semana}}</td>
    <td>{{line.p1}}</td>
    <td>{{line.p1_1}}</td>
    <td>{{line.p1_2}}</td>
    <td>{{line.p2}}</td>
    <td>{{line.p2_1}}</td>
    <td>{{line.p3}}</td>
    <td>{{line.p3_1}}</td>
    <td>{{line.p4}}</td>
    <td>{{line.p4_1}}</td>
    <td>{{line.p5}}</td>
    <td>{{line.p5_1}}</td>
	</tr>
    {%endfor%}
	</table>
	{%endif%}
    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
{%endblock%}

templates/cadastro/designar.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <p>data da geração: {{hoje}}</p>
    <form action="{% url 'cadastro:gerador' %}" method="post" novalidate>
        {% csrf_token %}
		<div>
        <table>
            <tr class="{% cycle 'row1' 'row2' %}">
			<td>
                <input type="radio" name="mes" value="1" checked>Janeiro<br>
                <input type="radio" name="mes" value="2">Fevereiro<br>
                <input type="radio" name="mes" value="3">Março<br>
                <input type="radio" name="mes" value="4">Abril<br>
                <input type="radio" name="mes" value="5">Maio<br>
                <input type="radio" name="mes" value="6">Junho<br>
            </td>
                <td>
                    <input type="radio" name="mes" value="7">Julho<br>
                    <input type="radio" name="mes" value="8">Agosto<br>
                    <input type="radio" name="mes" value="9">Setembro<br>
                    <input type="radio" name="mes" value="10">Outubro<br>
                    <input type="radio" name="mes" value="11">Novembro<br>
                    <input type="radio" name="mes" value="12">Dezembro<br>
                </td>
				</tr>
            <tr><td>
                <input type="text" name="ano" value={{ano}} size="5">
            </td></tr>
                <input type="submit" value="Gerar Planilha">
            </div>
        </table>
    </form>
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        {% load log %}
        {% get_admin_log 10 as admin_log for_user user %}
        {% if not admin_log %}
        <p>{% trans 'None available' %}</p>
        {% else %}
        <p>lateral</p>
        <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                {{ entry.object_repr }}
                {% else %}
                <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/cadastro/gerador - Copy.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}
{% block content %}
<div id="content-main">
    Voce esta trabalhando a partir do Terminal {{station}}
    
    <form action="{% url 'admin:gerador'%}" method="post" novalidate>
        {% csrf_token %}
        <table>
            <tr><td>
                <input type="radio" name="mes" value="1" checked>Janeiro<br>
                <input type="radio" name="mes" value="2">Fevereiro<br>
                <input type="radio" name="mes" value="3">Março<br>
                <input type="radio" name="mes" value="4">Abril<br>
                <input type="radio" name="mes" value="5">Maio<br>
                <input type="radio" name="mes" value="6">Junho<br>
            </td>
                <td>
                    <input type="radio" name="mes" value="7">Julho<br>
                    <input type="radio" name="mes" value="8">Agosto<br>
                    <input type="radio" name="mes" value="9">Setembro<br>
                    <input type="radio" name="mes" value="10">Outubro<br>
                    <input type="radio" name="mes" value="11">Novembro<br>
                    <input type="radio" name="mes" value="12">Dezembro<br>
                </td></tr>
            <tr><td>
                <input type="text" name="ano" value={{ano}} size="5">
            </td></tr>
            <div>
                <button type="search">Gerar Planilha</button>
            </div>
        </table>
    </form>
</div>
{% endblock %}
{% block sidebar %}
<div id="content-related">
    The sun doesn't reach it
</div>
{% endblock%}
{%block footer%}
<a href="{%url 'admin:index'%}">voltar </a>
{%endblock%}

templates/cadastro/gerador.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
<head>
    {% block title %}Testemunho Público{% endblock %}
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static " admin /css/rtl.css" %}{% endblock %}" />{% endif %}
    {% block extrahead %}{% endblock %}
    {% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static " admin /css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" type="text/css" href="{% static " admin /css/responsive_rtl.css" %}">{% endif %}
    {% endblock %}
    {% block blockbots %}
    <meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% block branding %} <h1 id="site-name"><a href="{% url 'admin:index' %}">{{ mes_label}}</a></h1>{% endblock %}

{%block content%}
<div id="content-main">
    <table align="center" border="3">
        <tr class="{% cycle 'row1' 'row2' %}">
            <td>Mes</td>
            <td>semana</td>
            <td>Periodo 1</td>
            <td>Periodo 1</td>
            <td>Periodo 1</td>
            <td>Periodo 2</td>
            <td>Periodo 2</td>
            <td>Periodo 3</td>
            <td>Periodo 3</td>
            <td>Periodo 4</td>
            <td>Periodo 4</td>
        </tr>
        {%for dia_mes,dia_semana,p1,p1_1,p1_2,p2,p2_1,p3,p3_1,p4,p4_1,p5,p5_1 in lista_mes%}
        <tr>
            <td>{{dia_mes|last}}</td>
            <td>{{dia_semana|last}}</td>
            <td>{{p1|last}}</td>
            <td>{{p1_1|last}}</td>
            <td>{{p1_2|last}}</td>
            <td>{{p2|last}}</td>
            <td>{{p2_1|last}}</td>
            <td>{{p4|last}}</td>
            <td>{{p4_1|last}}</td>
            <td>{{p5|last}}</td>
            <td>{{p5_1|last}}</td>
        </tr>
        {%endfor%}
    </table>
    <form method="post" action="{%url 'cadastro:confirmacao'%}">
        {%csrf_token%}
        <div>
            <table align="center" border="3">
                <tr class="{% cycle 'row1' 'row2'%}">
                    <td>Mes</td>
                    <td>Dia do Mes</td>
                    <td>semana</td>
                    <td>Periodo 1</td>
                    <td>Periodo 1</td>
                    <td>Periodo 1</td>
                    <td>Periodo 2</td>
                    <td>Periodo 2</td>
                    <td>Periodo 3</td>
                    <td>Periodo 3</td>
                    <td>Periodo 4</td>
                    <td>Periodo 4</td>
                    <td>Periodo 5</td>
                    <td>Periodo 5</td>
                </tr>
                {%for dia_mes,dia_semana,p1,p1_1,p1_2,p2,p2_1,p3,p3_1,p4,p4_1,p5,p5_1 in lista_mes%}
                <tr class="{% cycle 'row1' 'row2'%}">
                    <td><input type="text" name="mes" value="{{mes_label}}" size="3"></td>
                    <td><input type="text" name="dia_mes" value="{{dia_mes|last}}" size="3"></td>
                    <td><input type="text" name="dia_semana" value="{{dia_semana|last}}" size="13"></td>
                    <td><input type="text" name="p1" value="{{p1|last}}" size="10"></td>
                    <td><input type="text" name="p1_1" value="{{p1_1|last}}" size="10"></td>
                    <td><input type="text" name="p1_2" value="{{p1_2|last}}" size="10"></td>
                    <td><input type="text" name="p2" value="{{p2|last}}" size="10"></td>
                    <td><input type="text" name="p2_1" value="{{p2_1|last}}" size="10"></td>
                    <td><input type="text" name="p3" value="{{p3|last}}" size="10"></td>
                    <td><input type="text" name="p3_1" value="{{p3_1|last}}" size="10"></td>
                    <td><input type="text" name="p4" value="{{p4|last}}" size="10"></td>
                    <td><input type="text" name="p4_1" value="{{p4_1|last}}" size="10"></td>
                    <td><input type="text" name="p5" value="{{p5|last}}" size="10"></td>
                    <td><input type="text" name="p5_1" value="{{p5_1|last}}" size="10"></td>
                </tr>
                {%endfor%}
            </table>
        </div>
        <input type="submit" value="Gravar">
    </form>
    <div>Dia: {{hoje}}</div>
    {%endblock%}
</div>
{% block sidebar %}
<div id="content-related">
    Lista dos irmaos
    {%if lista%}
    <div class="module" id="recent-actions-module">
        {%for item_lista in lista%}
        <p>{{item_lista.irmao__nm}}</p>
        {%endfor%}
    </div>
</div>
{%endif%}
{%endblock%}

    {%block footer%}
<a href="{%url 'admin:index'%}">voltar </a>
    {%endblock%}

templates/cadastro/importar.html
{% extends "../admin/base_site.html" %}
{% load i18n static %}
{% block title %}Testemunho Público{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <form action="{%url 'cadastro:importar'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <input type="file" name="file_import" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"/>

        <p><button type="submit" name="import">Importar</button></p>
    </form>
</div>
<div class="results">
<table id="result_list">
<thead>
<tr>

{% for header in result_headers %}
<th scope="col" {{ header.class_attrib }}>
       <div class="sortoptions">
         <a class="sortremove" href="{{ header.url_remove }}" title="{% trans "Remove from sorting" %}"></a>
         {% if num_sorted_fields > 1 %}<span class="sortpriority" title="{% blocktrans with priority_number=header.sort_priority %}Sorting priority: {{ priority_number }}{% endblocktrans %}">{{ header.sort_priority }}</span>{% endif %}
         <a href="{{ header.url_toggle }}" class="toggle {% if header.ascending %}ascending{% else %}descending{% endif %}" title="{% trans "Toggle sorting" %}"></a>
       </div>
   <div class="text">{% if header.sortable %}<a href="{{ header.url_primary }}">{{ header.text|capfirst }}</a>{% else %}<span>{{ header.text|capfirst }}</span>{% endif %}</div>
   <div class="clear"></div>
</th>{% endfor %}
</tr>
</thead>

    <tbody>
    {%if context%}
    {%for lines in context%}
    <form action="{%url 'cadastro:gravar'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
    <tr><td colspan="{{ lines|length }}">{{ line.form.non_field_errors }}</td></tr>
    <tr class="{% cycle 'row1' 'row2' %}">
        {%for dia in lines %}
		<td>{%for per in dia.values%}{{per}}{%endfor%}</td>
        <!-- {%for per in dia.values%}<td>{{per}}</td>{%endfor%} -->
        {% endfor %}
    </tr>
    {%endfor%}
        <input type="submit" value="gravar" />
    </form>
    </tbody>
</table>
</div>
{% endif %}
{%endblock%}
{% block nav-global %}{% endblock %}
<script type="text/javascript">
// using jQuery
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
// set csrf header
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

// Ajax call here
$.ajax({
    url:"{% url 'members:saveAccount' %}",
    data: fd,
    processData: false,
    contentType: false,
    type: 'POST',
    success: function(data) {
        alert(data);
        }
    });
</script>

templates/cadastro/importar_origem.html
{% extends "../admin/base_site.html" %}

{% block title %}Testemunho Público{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Testemunho Público</a></h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <form action="{%url 'cadastro:importar'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <input type="file" name="file_import" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"/>

        <p><button type="submit" name="import">Importar</button></p>
    </form>
</div>

templates/cadastro/intermediate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tela de retorno de teste</title>
</head>
<body>
Tela de retorno de teste
</body>
</html>